version: '3.4'

services:
  moodsy_pg:
    container_name: moodsy_pg_container
    image: postgres:14.1-alpine3.15
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_HOST_AUTH_METHOD: trust
      PGUSER: postgres
    ports:
      - "5432:5432"
    volumes:
      - "${PWD}/data/initdb/:/docker-entrypoint-initdb.d/"
      - "moodsy_pg_data:/var/lib/postgresql/data/"

  moodsy_flask:
    container_name: moodsy_flask_container
    image: docker.io/bkin/moodsyflask:latest
    restart: unless-stopped
    environment:
      DATABASE_HOST: moodsy_pg
      DATABASE_PORT: 5432
      DATABASE_NAME: moody
      DATABASE_USER: postgres
      DATABASE_PASSWORD: 
      WTF_CSRF_SECRET_KEY: Outtakes-Reformist9-Huff-Machine
      SECRET_KEY: Outtakes-Reformist9-Huff-Machine
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 5000:5000
    volumes:
      - "${PWD}/container_entrypoint/:/app/custom_entrypoint/"
    depends_on:
      - moodsy_pg
    entrypoint: 
      - bash
      - /app/custom_entrypoint/entrypoint.sh
    networks:
      - network1
      - default


  # migrations:
  #   build:
  #     context: /app
  #   command: python -m flask db upgrade
  #   depends_on:
  #     - moodsy_flask
networks:
  default:
    name: moodsy_net
  network1:
    name: swag
    external: true
volumes:
  moodsy_pg_data: 
