"""empty message

Revision ID: 23a8dc454155
Revises: bc19ecc9f71f
Create Date: 2023-07-29 14:00:01.017950

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '23a8dc454155'
down_revision = 'bc19ecc9f71f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'moods', ['description'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'moods', type_='unique')
    # ### end Alembic commands ###
